/*! ModernGantt v2.1 | Author: Kashyap Makadia */
(function(){
'use strict';
const VERSION='2.1.0',AUTHOR='Kashyap Makadia',DAY=86400000;
const MONTHS=['January','February','March','April','May','June','July','August','September','October','November','December'];
const DEF={data:[],source:null,groupBy:[],fromField:'startDate',toField:'endDate',labelField:'Event',barText:null,barClassField:'customClass',barStyleField:'barStyle',barClass:null,barStyle:null,tooltipTemplate:null,tooltipField:null,popupTarget:null,popupClass:'mg-popup',popupTemplate:null,title:'',scale:'months',theme:'blue',stickyHeader:true,stickyTop:0,showScrollSlider:true,scrollSliderSteps:1000,showAccordionControls:true,timelineFitMode:'auto',minMonthWidth:null,maxMonthWidth:null,minWeekWidth:null,maxWeekWidth:null,minDayWidth:null,maxDayWidth:null,leftPanelWidth:'25%',leftPanelMinWidth:'240px',leftPanelMaxWidth:'560px',minTimelineWidth:1024,rowHeight:32,barHeight:20,headerRowHeight:28,weekPrefix:'W',showWeekPrefix:true,fullMonthNames:true,groupAccordion:true,collapseGroups:false,leafSortByFrom:true,focusCurrentYear:true,scrollToToday:false,showTodayMarker:true,oddEvenYearBackground:true,oddEvenMonthBackground:true,noDataMessage:'No event timeline data available.',loading:false,loadingMessage:'Loading events...',pagination:{enabled:false,pageSize:100},columns:null,extraColumns:[],onItemClick:null,onRender:null,onError:null};
const q=(s,e=document)=>e.querySelector(s),qa=(s,e=document)=>Array.from(e.querySelectorAll(s)),ce=(t,c)=>{const n=document.createElement(t);if(c)n.className=c;return n;},txt=(n,v)=>{n.textContent=v==null?'':String(v);return n;};
function safe(ctx,fn,err){try{return fn();}catch(e){console.error('ModernGantt '+ctx,e);if(typeof err==='function')err(e,{context:ctx,version:VERSION,author:AUTHOR});}}
function D(v){if(v instanceof Date)return v;if(typeof v==='number')return new Date(v);const m=String(v||'').match(/Date\((\d+)\)/);return m?new Date(+m[1]):new Date(v);}
function clean(d){return new Date(d.getFullYear(),d.getMonth(),d.getDate());}function add(d,n){const x=new Date(d);x.setDate(x.getDate()+n);return x;}function sow(d){const x=clean(d),k=(x.getDay()+6)%7;x.setDate(x.getDate()-k);return x;}function mi(d){return d.getFullYear()*12+d.getMonth();}function dim(d){return new Date(d.getFullYear(),d.getMonth()+1,0).getDate();}
function iso(d){const x=new Date(Date.UTC(d.getFullYear(),d.getMonth(),d.getDate())),k=x.getUTCDay()||7;x.setUTCDate(x.getUTCDate()+4-k);const y=new Date(Date.UTC(x.getUTCFullYear(),0,1));return Math.ceil((((x-y)/DAY)+1)/7);}
function blank(v){return v==null||v==='';}function key(v){return blank(v)?'(Blank)':String(v);}function minFrom(items,f){let m=null;items.forEach(i=>{const d=D(i[f]);if(!isNaN(d)&&(!m||d<m))m=d;});return m||new Date(8640000000000000);}
function sortBuckets(a,s){s=(s||'NONE-NULL').toUpperCase();return a.sort((x,y)=>{const xb=blank(x.raw),yb=blank(y.raw);if(xb&&!yb)return 1;if(!xb&&yb)return -1;if(s==='NONE-NULL')return x.order-y.order;const r=String(x.raw).localeCompare(String(y.raw),undefined,{numeric:true,sensitivity:'base'});return s==='DESC'?-r:r;});}
function clamp(v,min,max){return Math.min(Math.max(v,min),max);}
class ModernGantt{
static get version(){return VERSION;}static get author(){return AUTHOR;}
constructor(container,opt){this.container=typeof container==='string'?q(container):container;this.options={...DEF,...(opt||{}),pagination:{...DEF.pagination,...(((opt||{}).pagination)||{})}};this.raw=[...(this.options.data||this.options.source||[])];this.page=1;this.groupState=new Map();this.itemMap=new Map();this._resizeTimer=null;this.render();}
err(c,f){return safe(c,f,this.options.onError);}setData(data){this.raw=[...(data||[])];this.page=1;this.draw(true);}refresh(){this.draw(false);}setLoading(v,msg){this.options.loading=!!v;if(msg)this.options.loadingMessage=msg;this.draw(false);}setTheme(theme){this.options.theme=theme||'blue';this.container.className='modern-gantt mg-theme-'+this.options.theme+(this.options.stickyHeader?' mg-sticky-header':'');}scrollToCurrent(){this.scrollToDate(new Date());}scrollToCurrentYear(){this.scrollToDate(new Date(new Date().getFullYear(),0,1));}
expandAll(){this.build();this.rows.filter(r=>r.type==='group').forEach(r=>this.groupState.set(r.stateKey,false));this.draw(false);}collapseAll(){this.build();this.rows.filter(r=>r.type==='group').forEach(r=>this.groupState.set(r.stateKey,true));this.draw(false);}expandLevel(level){this.build();this.rows.filter(r=>r.type==='group'&&r.level===level).forEach(r=>this.groupState.set(r.stateKey,false));this.draw(false);}collapseLevel(level){this.build();this.rows.filter(r=>r.type==='group'&&r.level===level).forEach(r=>this.groupState.set(r.stateKey,true));this.draw(false);}
pageData(){const p=this.options.pagination;if(!p.enabled)return this.raw;const s=Math.max(1,p.pageSize||100);return this.raw.slice((this.page-1)*s,this.page*s);}
build(){const d=this.pageData(),o=this.options;this.itemMap.clear();this.rows=(o.groupBy&&o.groupBy.length)?this.group(d,o.groupBy,0,null,{}):d.map((x,i)=>({id:'r'+i,type:'leaf',level:0,label:x[o.labelField]||x.label||x.name||'',items:[x],path:{},parent:null}));}
group(data,defs,l,parent,path){let out=[],def=defs[l],map=new Map(),ord=0;data.forEach(it=>{const raw=it[def.field],k=key(raw);if(!map.has(k))map.set(k,{raw,key:k,order:ord++,items:[]});map.get(k).items.push(it);});let arr=[...map.values()];if(this.options.leafSortByFrom&&l===defs.length-1)arr.sort((a,b)=>minFrom(a.items,this.options.fromField)-minFrom(b.items,this.options.fromField));else sortBuckets(arr,def.sort);arr.forEach((b,i)=>{const leaf=l===defs.length-1,p={...path,[def.field]:b.raw},state=l+'|'+def.field+'|'+b.key,defVis=def.defaultVisible!==false;let collapsed=this.groupState.has(state)?this.groupState.get(state):!defVis;if(this.options.collapseGroups)collapsed=true;const r={id:'g'+l+'_'+i,type:leaf?'leaf':'group',level:l,label:b.key,path:p,parent,field:def.field,stateKey:state,collapsed,groupCss:def.groupCss||'',items:leaf?b.items.sort((a,b)=>D(a[this.options.fromField])-D(b[this.options.fromField])):[]};out.push(r);if(!leaf)out.push(...this.group(b.items,defs,l+1,r,p));});return out;}
visible(){return this.rows.filter(r=>{let p=r.parent;while(p){if(p.collapsed)return false;p=p.parent;}return true;});}
dataDateRange(){let min=null,max=null,o=this.options;this.raw.forEach(it=>{const a=D(it[o.fromField]),b=D(it[o.toField]);if(!isNaN(a)&&(!min||a<min))min=a;if(!isNaN(b)&&(!max||b>max))max=b;});return min&&max?{min,max}:null;}
range(){const r=this.dataDateRange(),y=new Date().getFullYear();if(!r)return{min:new Date(y,0,1),max:new Date(y,11,31)};return{min:new Date(r.min.getFullYear(),0,1),max:new Date(r.max.getFullYear(),11,31)};}
ticks(min,max){const a=[],s=this.options.scale;let d=s==='months'?new Date(min.getFullYear(),0,1):(s==='weeks'?sow(min):clean(min));while(d<=max){a.push(new Date(d));d=s==='months'?new Date(d.getFullYear(),d.getMonth()+1,1):add(d,s==='weeks'?7:1);}return a;}
unitWidth(tickCount){const o=this.options,s=o.scale,count=Math.max(tickCount,1);let min,max;if(s==='months'){min=o.minMonthWidth??90;max=o.maxMonthWidth??220;}else if(s==='weeks'){min=o.minWeekWidth??54;max=o.maxWeekWidth??120;}else{min=o.minDayWidth??28;max=o.maxDayWidth??72;}const fixed=Math.max(o.minTimelineWidth/count,min);if(o.timelineFitMode==='fixed')return fixed;const host=this.right?this.right.clientWidth:(this.container.clientWidth||o.minTimelineWidth);const available=Math.max(host,o.minTimelineWidth);const fitted=available/count;return clamp(Math.max(fitted,min),min,max);}
x(v,min,px){const d=D(v),s=this.options.scale;if(s==='months')return (mi(d)-mi(min)+(d.getDate()-1)/dim(d))*px;return ((clean(d)-(s==='weeks'?sow(min):clean(min)))/(s==='weeks'?7*DAY:DAY))*px;}
cols(){const o=this.options;return o.columns?[...o.columns,...o.extraColumns]:[{field:'__label',title:'Name',width:'1.5fr'},...o.extraColumns];}
render(){this.err('render',()=>{const o=this.options,c=this.container;c.innerHTML='';c.className='modern-gantt mg-theme-'+(o.theme||'blue')+(o.stickyHeader?' mg-sticky-header':'');c.dataset.version=VERSION;c.dataset.author=AUTHOR;c.style.setProperty('--mg-sticky-top',(o.stickyTop||0)+'px');[['--mg-left-width',o.leftPanelWidth],['--mg-left-min',o.leftPanelMinWidth],['--mg-left-max',o.leftPanelMaxWidth],['--mg-min-timeline',o.minTimelineWidth+'px'],['--mg-row-height',o.rowHeight+'px'],['--mg-bar-height',o.barHeight+'px'],['--mg-header-row-height',o.headerRowHeight+'px']].forEach(x=>c.style.setProperty(x[0],x[1]));const tb=ce('div','mg-toolbar'),title=txt(ce('div','mg-title'),o.title),actions=ce('div','mg-actions');this.scrollSlider=ce('input','mg-scroll-slider');this.scrollSlider.type='range';this.scrollSlider.min='0';this.scrollSlider.max=String(o.scrollSliderSteps||1000);this.scrollSlider.value='0';if(o.showScrollSlider!==false)actions.append(this.scrollSlider);if(o.showAccordionControls!==false){const ex=txt(ce('button','mg-accordion-btn'),'⤢'),co=txt(ce('button','mg-accordion-btn'),'⤡');ex.title='Expand all groups';co.title='Collapse all groups';ex.onclick=e=>{e.stopPropagation();this.expandAll();};co.onclick=e=>{e.stopPropagation();this.collapseAll();};actions.append(ex,co);}['days','weeks','months'].forEach(s=>{const b=txt(ce('button','mg-scale-btn'),s[0].toUpperCase()+s.slice(1));b.dataset.scale=s;actions.append(b);});tb.append(title,actions);this.headerBand=ce('div','mg-header-band');this.leftHeadHost=ce('div','mg-left-head-host');this.rightHeadHost=ce('div','mg-right-head-host');this.headerBand.append(this.leftHeadHost,this.rightHeadHost);this.body=ce('div','mg-body');this.leftRows=ce('div','mg-left-rows');this.right=ce('div','mg-right');this.body.append(this.leftRows,this.right);this.empty=txt(ce('div','mg-empty'),o.noDataMessage);this.loader=txt(ce('div','mg-loading'),o.loadingMessage);this.pager=ce('div','mg-pager');c.append(tb,this.headerBand,this.body,this.empty,this.loader,this.pager);tb.onclick=e=>{if(e.target.dataset.scale){o.scale=e.target.dataset.scale;this.draw(false);}};this.scrollSlider.addEventListener('input',()=>this.applyScrollSlider());this.right.addEventListener('scroll',()=>{this.rightHeadHost.scrollLeft=this.right.scrollLeft;this.syncScrollSlider();},{passive:true});window.addEventListener('resize',()=>{clearTimeout(this._resizeTimer);this._resizeTimer=setTimeout(()=>this.draw(false),120);});this.draw(true);});}
draw(initialFocus){this.err('draw',()=>{this.build();qa('.mg-scale-btn',this.container).forEach(b=>b.classList.toggle('active-scale',b.dataset.scale===this.options.scale));const no=!this.raw.length;this.empty.style.display=no&&!this.options.loading?'block':'none';this.loader.style.display=this.options.loading?'block':'none';this.headerBand.style.display=this.body.style.display=no||this.options.loading?'none':'flex';if(!no&&!this.options.loading){this.drawHeaders();this.drawRows(initialFocus);}this.drawPager();if(typeof this.options.onRender==='function')this.options.onRender(this,{rows:this.rows,visibleRows:this.visible(),page:this.page,scale:this.options.scale,range:this.range(),version:VERSION,author:AUTHOR});});}
drawHeaders(){const cols=this.cols(),o=this.options;this.leftHeadHost.innerHTML='';this.leftHeadHost.style.setProperty('--mg-left-cols',cols.map(c=>c.width||'1fr').join(' '));const lh=ce('div','mg-left-head');cols.forEach(c=>lh.append(txt(ce('div','mg-cell'),c.title||c.field||'')));this.leftHeadHost.append(lh);const rg=this.range(),ts=this.ticks(rg.min,rg.max),px=this.unitWidth(ts.length),total=ts.length*px;this._timeline={rg,ts,px,total};this.rightHeadHost.innerHTML='';const th=this.header(ts,px);th.style.width=total+'px';this.rightHeadHost.append(th);this.rightHeadHost.scrollLeft=this.right.scrollLeft;this.container.style.setProperty('--mg-header-rows',o.scale==='months'?2:3);}
drawRows(initialFocus){const cols=this.cols(),vis=this.visible(),o=this.options,t=this._timeline;this.leftRows.innerHTML='';this.leftRows.style.setProperty('--mg-left-cols',cols.map(c=>c.width||'1fr').join(' '));vis.forEach((r,i)=>{const row=ce('div','mg-left-row '+(r.type==='group'?'mg-group-row ':'')+(r.groupCss||''));row.style.setProperty('--mg-indent',(r.level*18)+'px');cols.forEach((c,ci)=>{const cell=ce('div','mg-cell '+(c.className||''));let v=c.field==='__label'?r.label:(r.type==='leaf'&&r.items[0]?r.items[0][c.field]:r.path[c.field]);if(typeof c.formatter==='function')v=c.formatter(r);if(ci===0){cell.classList.add('mg-first-cell');if(r.type==='group')cell.append(txt(ce('span','mg-toggle'),r.collapsed?'▸':'▾'));cell.append(document.createTextNode(v??''));}else txt(cell,v);row.append(cell);});if(o.groupAccordion&&r.type==='group')row.onclick=()=>{r.collapsed=!r.collapsed;this.groupState.set(r.stateKey,r.collapsed);this.draw(false);};this.leftRows.append(row);});this.right.innerHTML='';const grid=ce('div','mg-grid');grid.style.width=t.total+'px';grid.style.height=vis.length*o.rowHeight+'px';vis.forEach((row,ri)=>{const line=ce('div','mg-time-row '+(row.type==='group'?'mg-group-line':''));line.style.top=(ri*o.rowHeight)+'px';line.style.height=o.rowHeight+'px';t.ts.forEach(dt=>{const cell=ce('div','mg-grid-cell '+(o.oddEvenYearBackground?'yr'+(dt.getFullYear()%2):'')+' '+(o.oddEvenMonthBackground?'mo'+(dt.getMonth()%2):''));cell.style.width=t.px+'px';line.append(cell);});grid.append(line);if(row.type==='leaf')row.items.forEach(it=>{const st=D(it[o.fromField]),en=D(it[o.toField]);if(isNaN(st)||isNaN(en))return;let cls=it[o.barClassField]||'';if(typeof o.barClass==='function')cls+=' '+(o.barClass(it,row)||'');const bar=txt(ce('div','mg-bar '+cls),this.label(it,row)),title=this.tip(it,row);if(title)bar.title=title;if(it[o.barStyleField])bar.setAttribute('style',it[o.barStyleField]);if(typeof o.barStyle==='function')Object.assign(bar.style,o.barStyle(it,row)||{});bar.style.left=this.x(st,t.rg.min,t.px)+'px';bar.style.top=(ri*o.rowHeight+(o.rowHeight-o.barHeight)/2)+'px';bar.style.width=Math.max(this.x(en,t.rg.min,t.px)-this.x(st,t.rg.min,t.px),t.px*.5)+'px';bar.style.height=o.barHeight+'px';bar.onclick=e=>{e.stopPropagation();if(o.popupTarget){const p=q(o.popupTarget);if(p){p.classList.add(o.popupClass);p.innerHTML=typeof o.popupTemplate==='function'?o.popupTemplate(it,row):'<pre>'+JSON.stringify(it,null,2)+'</pre>';p.style.display='block';}}if(typeof o.onItemClick==='function')o.onItemClick(it,{row,item:it,bar,event:e},e);this.container.dispatchEvent(new CustomEvent('gantt:itemclick',{detail:{item:it,row,bar,event:e}}));};grid.append(bar);});});if(o.showTodayMarker){const now=new Date();if(now>=t.rg.min&&now<=t.rg.max){const mk=ce('div','mg-today');mk.style.left=this.x(now,t.rg.min,t.px)+'px';grid.append(mk);}}this.right.append(grid);const fd=initialFocus?this.focusDate():null;if(fd)this.scrollToDate(fd);this.syncScrollSlider();}
header(ts,px){const o=this.options,w=ce('div','mg-time-header-wrap'),yr=ce('div','mg-time-head mg-year-row'),mr=ce('div','mg-time-head mg-month-row'),ur=ce('div','mg-time-head mg-unit-row'),span=(row,v,c,cl)=>{const cell=txt(ce('div','mg-time-cell '+cl),v);cell.style.width=(c*px)+'px';row.append(cell);};let y=null,yc=0,m=null,mc=0;ts.forEach(t=>{const yy=t.getFullYear(),mm=t.getMonth();if(y===null){y=yy;yc=1;}else if(y===yy)yc++;else{span(yr,y,yc,'mg-year-cell mg-y'+(y%2));y=yy;yc=1;}if(m===null){m=mm;mc=1;}else if(m===mm)mc++;else{span(mr,o.fullMonthNames?MONTHS[m]:m+1,mc,'mg-month-cell mg-m'+m);m=mm;mc=1;}if(o.scale!=='months'){const lab=o.scale==='weeks'?(o.showWeekPrefix?o.weekPrefix:'')+iso(t):t.getDate(),c=txt(ce('div','mg-time-cell mg-unit-cell'),lab);c.style.width=px+'px';ur.append(c);}});if(y!==null)span(yr,y,yc,'mg-year-cell mg-y'+(y%2));if(m!==null)span(mr,o.fullMonthNames?MONTHS[m]:m+1,mc,'mg-month-cell mg-m'+m);w.append(yr,mr);if(o.scale!=='months')w.append(ur);return w;}
label(it,row){const o=this.options;if(typeof o.barText==='function')return o.barText(it,row);if(o.barText&&it[o.barText]!=null)return it[o.barText];return o.labelField?it[o.labelField]:(it.label||row.label);}tip(it,row){const o=this.options;if(typeof o.tooltipTemplate==='function')return o.tooltipTemplate(it,row);if(o.tooltipField&&it[o.tooltipField]!=null)return it[o.tooltipField];return this.label(it,row);}focusDate(){const o=this.options,now=new Date();if(o.scrollToToday)return now;if(o.focusCurrentYear)return new Date(now.getFullYear(),0,1);return null;}
scrollToDate(date){const t=this._timeline;if(!t)return;const x=this.x(date,t.rg.min,t.px);if(isFinite(x)&&date>=t.rg.min&&date<=t.rg.max){this.right.scrollLeft=Math.max(0,x-this.right.clientWidth/2);this.rightHeadHost.scrollLeft=this.right.scrollLeft;this.syncScrollSlider();}}
applyScrollSlider(){const max=this.right.scrollWidth-this.right.clientWidth;if(max<=0)return;const steps=Math.max(1,parseInt(this.scrollSlider.max||'1000',10));this.right.scrollLeft=(Number(this.scrollSlider.value)/steps)*max;}
syncScrollSlider(){if(!this.scrollSlider)return;const max=this.right.scrollWidth-this.right.clientWidth,steps=Math.max(1,parseInt(this.scrollSlider.max||'1000',10));this.scrollSlider.disabled=max<=0;this.scrollSlider.value=max>0?String(Math.round((this.right.scrollLeft/max)*steps)):'0';}
drawPager(){const p=this.options.pagination,pg=this.pager;pg.innerHTML='';if(!p.enabled){pg.style.display='none';return;}pg.style.display='flex';const pages=Math.max(1,Math.ceil(this.raw.length/(p.pageSize||100))),prev=txt(ce('button'),'Prev'),next=txt(ce('button'),'Next'),info=txt(ce('span'),`Page ${this.page} / ${pages}`);prev.disabled=this.page<=1;next.disabled=this.page>=pages;prev.onclick=()=>{this.page--;this.draw(true);};next.onclick=()=>{this.page++;this.draw(true);};pg.append(prev,info,next);}
}
window.ModernGantt=ModernGantt;
})();
